### PR TITLE
Added chromatic aberration correction to the frag shader.

### PR DESCRIPTION
**Pull request by prisonerjohn**
I think... it looks crisper to me but then again my eyes aren't the best.

I ported over this code, which I found in the [OVR docs](http://static.oculusvr.com/sdk-downloads/documents/Oculus_SDK_Overview.pdf).

```
Texture2D Texture : register(t0);
SamplerState Linear : register(s0);
float2 LensCenter;
float2 ScreenCenter;
float2 Scale;
float2 ScaleIn;
float4 HmdWarpParam;
float4 ChromAbParam;

float4 main(in float4 oPosition : SV_Position, in float4 oColor : COLOR,
            in float2 oTexCoord : TEXCOORD0) : SV_Target
{
    float2 theta = (oTexCoord - LensCenter) * ScaleIn; // Scales to [-1, 1]
    float  rSq = theta.x * theta.x + theta.y * theta.y;
    float2 theta1 = theta * (HmdWarpParam.x + HmdWarpParam.y * rSq +
        HmdWarpParam.z * rSq * rSq +
        HmdWarpParam.w * rSq * rSq * rSq);

    // Detect whether blue texture coordinates are out of range
    // since these will scaled out the furthest.
    float2 thetaBlue = theta1 * (ChromAbParam.z + ChromAbParam.w * rSq);
    float2 tcBlue = LensCenter + Scale * thetaBlue;
    if (any(clamp(tcBlue, ScreenCenter -float2(0.25,0.5),
            ScreenCenter+float2(0.25, 0.5)) - tcBlue))
        return 0;

    // Now do blue texture lookup.
    float  blue = Texture.Sample(Linear, tcBlue).b;
    // Do green lookup (no scaling).
    float2 tcGreen = LensCenter + Scale * theta1;
    float  green = Texture.Sample(Linear, tcGreen).g;
    // Do red scale and lookup.
    float2 thetaRed = theta1 * (ChromAbParam.x + ChromAbParam.y * rSq);
    float2 tcRed = LensCenter + Scale * thetaRed;
    float  red = Texture.Sample(Linear,o tcRed).r;

    return float4(red, green, blue, 1); 
}
```

One thing I noticed is that it always returns alpha 1. Is this the behaviour we want? Other options would be to get the min/max/avg of the three looked up pixels.

### CODE REVIEW

**Comment by prisonerjohn** [comment]
Hold on a sec! I just found the answer to my alpha question (and a GLSL shader!) in one of the samples. Adding another commit.

**Comment by prisonerjohn** [comment]
OK ready!

**Comment by ghost** [comment]
i love you.

**Comment by obviousjim** [comment]
So boss

On Tuesday, November 12, 2013, Jason Walters wrote:

> i love you.
> 
> On Tue, Nov 12, 2013 at 1:05 PM, Elie Zananiri <notifications@github.com<javascript:_e({}, 'cvml', 'notifications@github.com');>>wrote:
> 
> > OK ready!
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/obviousjim/ofxOculusRift/pull/6#issuecomment-28317490>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/obviousjim/ofxOculusRift/pull/6#issuecomment-28318556
> .

## 
- James

**Comment by prisonerjohn** [comment]
Aw shucks, thanks guys, love you too. Make sure it works!

**Comment by obviousjim** [comment]
yank!

**Pull request merged**
